config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "pages#home"
  get 'pages/home'
  get 'pages/about'
  get '/contact', to: "pages#contact"
  post '/send', to:"pages#send_contact"
  get '/message_send', to: "pages#message_send"
  get '/gestion-locative', to:  "pages#gestion_locative"
  get '/gestion-locative/:ville',to: "pages#gestion_locative_ville", as: :gestion_loc_ville

  get '/mentions',to: "pages#mentions"
  get '/confidentialite', to: "pages#confidentialite"
  get '/cookies',to:"pages#cookies"
  get '/plan-site',to:"pages#plan_site"

  get 'components', to: "pages#components"

  resources :admins do
    resources :annonces
    #collection do
      #get "annonces", to: "admins#annonces"
    #end
  end
  get 'locations', to: "locations#index"
  get 'locations/appartements', to: "locations#appartements"
  get 'locations/maisons', to: "locations#maisons"

  get "commerces", to: "commerces#index"

  resources :agences do
    collection do
      get "agence-immobiliere-strasbourg", to: "agences#orangerie", as: "strasbourg"
      get "agence-immobiliere-strasbourg-neudorf", to: "agences#neudorf", as: "neudorf"
      get "agence-immobiliere-strasbourg-krutenau", to: "agences#krutenau", as: "krutenau"
      get "agence-immobiliere-strasbourg-orangerie", to: "agences#orangerie", as: "orangerie"
      get "agence-immobiliere-wissembourg", to: "agences#wissembourg", as: "wissembourg"
      get "agence-immobiliere-molsheim", to: "agences#molsheim", as: "molsheim"
      get "agence-immobiliere-colmar", to: "agences#colmar", as: "colmar"
      get "agence-immobiliere-haguenau", to: "agences#haguenau", as: "haguenau"
      get "agence-immobiliere-schiltigheim", to: "agences#schiltigheim", as: "schiltigheim"
      get "agence-immobiliere-altkirch", to: "agences#altkirch", as: "altkirch"
      get "agence-immobiliere-brumath", to: "agences#brumath", as: "brumath"
      get "agence-immobiliere-barr", to: "agences#barr", as: "barr"
      get "agence-immobiliere-erstein", to: "agences#erstein", as: "erstein"
      get "agence-immobiliere-cernay", to: "agences#cernay", as: "cernay"
    end
  end
  get "achat-immobilier", to: "achats#index", as: :annonces
  get "achat-immobilier/:id", to: "achats#show", as: :achat_show
  get "achat-appartements", to: "achats#appartements", as: :appartements
  post "rent-filter", to: "achats#rent_filter", as: :rent_filter
  get "achat-maisons", to: "achats#maisons", as: :maisons
  get "achat-terrains", to: "achats#terrains", as: :terrains
  get "achat-test", to: "achats#annonces_test"
  post "turbo_list", to: "achats#turbo_list"

  scope "achat" do
    get "/alsace", to: "achats#alsace"
    get "/bas-rhin", to: "achats#bas_rhin"
    get "/haut-rhin", to: "achats#haut_rhin"
    get "/strasbourg", to: "achats#strasbourg"
    get "/test", to: "achats#test"
    scope "strasbourg" do
      get '/:quartier', to: "achats#strasbourg_quartier", as: :strasbourg_quartier
    end
  end

  post "full_list", to: "pages#full_list"

  
end

app/views/admins/index.html.erb
<h1>Admins#index</h1>
<p>Find me in app/views/admins/index.html.erb</p>
<%= current_admin.email %>

app/views/admins/show.html.erb
<section class="inside">
    <h1>Espace Admin</h1>
    <%= link_to "Créer une annonce immobiliere",new_admin_annonce_path(params[:id]), class:"btn white" %>
    <%= link_to "Créer une annonce de location","", class:"btn white" %>
    <p></p><%= current_admin.email %></p>
</section>
<section class="inside">

<table>
    <thead>
        <tr>
            <th>Nom</th>
            <th>Prix</th>
            <th>Bien</th>
            <th>Ville</th>
            <th>Vues</th>
            <th>Options</th>
        </tr>
    </thead>
    <tbody>
        <% @annonces.each do |annonce|%>
            <tr>
                <td><%= annonce.titre %></td>
                <td><%= annonce.price %></td>
                <td><%= annonce.type_bien %></td>
                <td><%= annonce.city %></td>
                <td><%= @vues.where_props(annonce_id: annonce.id).count %></td>
                <td>Voir 
                <%= link_to "Editer",edit_admin_annonce_path(current_admin,annonce)%>
                <%= link_to "Supprimer",
                    admin_annonce_path(current_admin,annonce),
                    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
                %></td>
            </tr>
        <%end%>
    </tbody>
</table>
</section>