config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "pages#home"
  get 'pages/home'
  get 'pages/about'
  get '/contact', to: "pages#contact"
  post '/send', to:"pages#send_contact"
  get '/message_send', to: "pages#message_send"
  get '/gestion-locative', to:  "pages#gestion_locative"
  get '/gestion-locative/:ville',to: "pages#gestion_locative_ville", as: :gestion_loc_ville

  get '/mentions',to: "pages#mentions"
  get '/confidentialite', to: "pages#confidentialite"
  get '/cookies',to:"pages#cookies"
  get '/plan-site',to:"pages#plan_site"

  get 'components', to: "pages#components"

  resources :admins do
    resources :annonces
    #collection do
      #get "annonces", to: "admins#annonces"
    #end
  end
  get 'locations', to: "locations#index"
  get 'locations/appartements', to: "locations#appartements"
  get 'locations/maisons', to: "locations#maisons"

  get "commerces", to: "commerces#index"

  resources :agences do
    collection do
      get "agence-immobiliere-strasbourg", to: "agences#orangerie", as: "strasbourg"
      get "agence-immobiliere-strasbourg-neudorf", to: "agences#neudorf", as: "neudorf"
      get "agence-immobiliere-strasbourg-krutenau", to: "agences#krutenau", as: "krutenau"
      get "agence-immobiliere-strasbourg-orangerie", to: "agences#orangerie", as: "orangerie"
      get "agence-immobiliere-wissembourg", to: "agences#wissembourg", as: "wissembourg"
      get "agence-immobiliere-molsheim", to: "agences#molsheim", as: "molsheim"
      get "agence-immobiliere-colmar", to: "agences#colmar", as: "colmar"
      get "agence-immobiliere-haguenau", to: "agences#haguenau", as: "haguenau"
      get "agence-immobiliere-schiltigheim", to: "agences#schiltigheim", as: "schiltigheim"
      get "agence-immobiliere-altkirch", to: "agences#altkirch", as: "altkirch"
      get "agence-immobiliere-brumath", to: "agences#brumath", as: "brumath"
      get "agence-immobiliere-barr", to: "agences#barr", as: "barr"
      get "agence-immobiliere-erstein", to: "agences#erstein", as: "erstein"
      get "agence-immobiliere-cernay", to: "agences#cernay", as: "cernay"
    end
  end
  get "achat-immobilier", to: "achats#index", as: :annonces
  get "achat-immobilier/:id", to: "achats#show", as: :achat_show
  get "achat-appartements", to: "achats#appartements", as: :appartements
  post "rent-filter", to: "achats#rent_filter", as: :rent_filter
  get "achat-maisons", to: "achats#maisons", as: :maisons
  get "achat-terrains", to: "achats#terrains", as: :terrains
  get "achat-test", to: "achats#annonces_test"
  post "turbo_list", to: "achats#turbo_list"

  scope "achat" do
    get "/alsace", to: "achats#alsace"
    get "/bas-rhin", to: "achats#bas_rhin"
    get "/haut-rhin", to: "achats#haut_rhin"
    get "/strasbourg", to: "achats#strasbourg"
    get "/test", to: "achats#test"
    scope "strasbourg" do
      get '/:quartier', to: "achats#strasbourg_quartier", as: :strasbourg_quartier
    end
  end

  post "full_list", to: "pages#full_list"

  
end

app/controllers/achats_controller.rb
class AchatsController < ApplicationController
  def index
    @page_title = "Achat immobilier | Marine Weishaar Immobilier"
    @cover = "https://as2.ftcdn.net/v2/jpg/06/59/15/57/1000_F_659155771_tZmCC9cXPhBTqhS5DQIaruhiSmj6rMBK.jpg"
    if params[:query].present? && params[:query]["address"] != ""
      @address = params[:query][:address]
      coordinates = Geocoder.search(@address).first.coordinates if @address != ""
      
      if @address != ""
        @annonces = Annonce.near(coordinates, 10)
      else
        @annonces = Annonce.all
      end

      case params[:query][:action]
      when "Louer"
        redirect_to locations_path()
      when "Acheter"
        #params[:query].delete("action")
        if params[:query][:type_bien].present? && params[:query][:type_bien] != "" && params[:query][:type_bien] != "Type de bien"
          @annonces = @annonces.where(type_bien: params[:query][:type_bien].downcase)
          @type_bien = params[:query][:type_bien].downcase
        else
          @type_bien = "all"
          #@annonces = Annonce.all
        end

        params[:query].delete("action")
        #params[:query].delete("type_bien")

        if params[:query]["nb_pieces"].present? && params[:query]["nb_pieces"] != ""
          @annonces = @annonces.where("nb_pieces >= ?", params[:query]["nb_pieces"])
        end

        if params[:query][:surface].present? && params[:query][:surface] != ""
          @annonces = @annonces.where("surface >= ?", params[:query][:surface].to_f)
        end

        if params[:query]["budget_min"].present? && params[:query]["budget_min"] != ""
          #@annonces = @annonces.where(" >= ?", params[:query]["nb_pieces"])
          min_price = Money.new(params[:query]["budget_min"])*100
          #fail
          array_annonces = []
          #@annonces = @annonces.where("price.fractional >= ?",min_price.fractional)
          @annonces.each do |annonce|
            array_annonces << annonce if annonce.price >= min_price
          end
          @annonces = Annonce.where(id: array_annonces.map(&:id))
        end

        if params[:query]["budget_max"].present? && params[:query]["budget_max"] != ""
          max_price = Money.new(params[:query]["budget_max"])*100
          array_annonces = []
          @annonces.each do |annonce|
            array_annonces << annonce if annonce.price <= max_price
          end
          @annonces = Annonce.where(id: array_annonces.map(&:id))
        end

        if params[:query]["surface"].present? && params[:query]["surface"] != ""
          @annonces = @annonces.where("surface >= ?", params[:query]["surface"].to_f)
        end

        #params[:query].delete("action")
        #User.where(["name LIKE ?", "%#{params[:query]}%"]).where(:admin => [nil, false])
      else
        print('It is not a string or number')
      end

      @markers = @annonces.geocoded.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude,
          info_window_html: render_to_string(partial: "shared/info_window", locals: {flat: flat}),
          marker_html: render_to_string(partial: "shared/marker", locals: {flat: flat})
        }
      end

    else
      @annonces = Annonce.all
      @markers = @annonces.geocoded.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude,
          info_window_html: render_to_string(partial: "shared/info_window", locals: {flat: flat}),
          marker_html: render_to_string(partial: "shared/marker", locals: {flat: flat})
        }
      end
      add_breadcrumb "Nos annonces immobilières", annonces_path
    end
    
    #if params[:query].present?
    #  action_switch = params[:query][:action]
    #end

    #if action_switch == "Acheter"
      #bien = params[:query][:type_bien].downcase
    #elsif action_switch == "Louer"
      #redirect_to locations_path()
    #elsif action_switch == "Location Professionnelle"
    #elsif action_switch == "Achat Neuf"
    #elsif action_switch == "Achat Ancien"
    #else
    #  redirect_to annonces_path
    #end

    # The `geocoded` scope filters only flats with coordinates
  end

  def show
    @annonce = Annonce.find(params[:id])
      @marker = [{
        lat: @annonce.latitude,
        lng: @annonce.longitude,
        info_window_html: render_to_string(partial: "shared/info_window", locals: {flat: @annonce}),
        marker_html: render_to_string(partial: "shared/marker", locals: {flat: @annonce})
      }]
    ahoy.track "annonce vue", title: @annonce.titre, annonce_id:@annonce.id
  end

  def rent_filter
    annonces = []
 
    biens = params[:annonces_filtres].keys[0..5]
    options = params[:annonces_filtres].keys[3..-1]
   
    biens.each do |type_bien|
      if params[:annonces_filtres][type_bien] == "1"
        annonces << Annonce.where(type_bien: type_bien)
      end
    end
    @annonces = annonces.flatten
    options.each do |option|
      if params[:annonces_filtres][option] != "0" && params[:annonces_filtres][option] != ""
        #fail
      end
    end
    #if params[:type_bien].present?
    #  @annonces = Annonce.where(type_bien: params[:type_bien])
    #else
    #  @annonces = Annonce.all
    #end
    
    respond_to do |format|
      #format.turbo_stream
      format.turbo_stream do
        render turbo_stream: turbo_stream.update(:annonces_list_index, partial: "achats/annonces",
          locals: { annonces: @annonces })
      end
      format.html {}
      #format.turbo_stream do
      #  render turbo_stream: turbo_stream.update("annonces_list_index", partial: "achats/annonces", locals: { annonces: @annonces })
      #end
      #format.html { redirect_to messages_url }
    end

  end
  def maisons
  end
  def terrains
  end

  def turbo_list
  end

  def alsace
  end

  def bas_rhin
  end

  def haut_rhin
  end

  def strasbourg
    @page_title = "Achat d'appartements et maisons à Strasbourg | Marine Weishaar Immobilier"
    @annonces = Annonce.all
    @quartiers = YAML.load_file('config/datas/quartiers.yml')
    @intro_text = "<p>Vous recherchez un <strong>appartement, une maison ou un bien commercial</strong> à <strong>Strasbourg</strong> ? Que vous soyez à la recherche de votre premier logement, d’un investissement locatif ou d'une propriété de prestige, nous vous offrons un accompagnement personnalisé pour concrétiser votre projet immobilier.</p>"
    add_breadcrumb "Nos annonces immobilières", annonces_path
    add_breadcrumb "Strasbourg", strasbourg_path
  end

  def strasbourg_quartier
    quartier_yml = YAML.load_file('config/datas/quartiers.yml')
    urls =  quartier_yml.map { |_, v| v["url"] }
    
    @quartier_name = quartier_yml.find { |k, v| v["url"] == params[:quartier] }&.first
    
    @quartier_text = YAML.load_file('config/datas/quartiers.yml')[@quartier_name]["text"]

    @cover = YAML.load_file('config/datas/quartiers.yml')[@quartier_name]["cover"]
    
    @annonces = Annonce.all
    @autres_quartiers = YAML.load_file('config/datas/quartiers.yml')

    @page_title = "Achat & location d'appartements et maisons | #{@quartier_name}, Strasbourg | Marine Weishaar Immobilier"
    add_breadcrumb "Accueil", root_path
    add_breadcrumb "Nos annonces immobilières", annonces_path
    add_breadcrumb "Strasbourg", strasbourg_path
    add_breadcrumb "#{@quartier_name}", @quartier_name.include?(" ") ? strasbourg_quartier_path(@quartier_name.downcase.gsub!(" ","-")) : strasbourg_quartier_path(@quartier_name.downcase)
  end

 
  
  def test
  end

  def annonces_test
  end
end

app/helpers/achats_helper.rb
module AchatsHelper
end

app/views/achats/_annonces.html.erb
<% annonces.each do |annonce| %>
    <li>
        <%= link_to achat_show_path(annonce) do %>
            <%= render partial: "achats/annonce", locals: {annonce: annonce} %>
        <% end %>
    </li>
<% end %>

app/views/achats/_autres_quartiers.html.erb
<div class="autres_quartiers">
    <h2>Les autres quartiers de Strasbourg</h2>
    <ul class="">
        <% locals[:quartiers].each do |quartier| %>
            <li>
                <%= image_tag quartier[1]["cover"],width: 200, height:200; %>
                <div class="autres_quartiers_text">
                    <h3><%= quartier[0] %></h3>
                </div>
            </li>
        <% end %>
    </ul>
</div>

app/views/achats/alsace.html.erb
<h1>Achats#alsace</h1>
<p>Find me in app/views/achats/alsace.html.erb</p>

app/views/achats/appartements.turbo_stream.erb
<%= turbo_stream.update "annonces_list_index" do %>
  <%= render partial: "achats/annonces", locals: { annonces: @annonces } %>
<% end %>

app/views/achats/bas_rhin.html.erb
<h1>Achats#bas_rhin</h1>
<p>Find me in app/views/achats/bas_rhin.html.erb</p>

app/views/achats/full_list.html.erb
<turbo-frame id="view_more">
  <p>
    That's all! Nothing else to show.
  </p>
</turbo-frame>

app/views/achats/haut_rhin.html.erb
<h1>Achats#haut_rhin</h1>
<p>Find me in app/views/achats/haut_rhin.html.erb</p>

app/views/achats/index.html.erb
<div class="achat_index">
    <section class="inside">
        <h1 data-address="<%= @address %>">Annonces immobilières</h1>
        <%= link_to "Strasbourg", strasbourg_path() %>
        <%= simple_form_for :query, :url => annonces_path, method: :get do |f| %>
            <%= f.input :address,
                    input_html: {data: {address_autocomplete_target: "address"}},
                    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]},class: "d-none"} 
                %>
            <%= f.submit "Rechercher", class: "btn btn-primary" %> 
        <% end %>
        <div data-controller="filters">
            <ul class="filtre_tags">
                <%= simple_form_for :annonces_filtres,class:"form_filters" ,url: rent_filter_path,data:{filters_target: "category_form"} do |f| %>
                    <div class="visible_filters">
                        <% if @type_bien == "maison" || @type_bien == "all" || @type_bien == nil %>
                            <div class="filtre_btn filter_actif peche">
                                <div>
                                    <span class="close_icon"><%= image_tag "pictos/circle-xmark-regular.svg"%></span>
                                    <%= f.input :maison, as: :boolean,label:"Maisons", input_html: { data: {action: "change->filters#checkedSelect"},:checked => true } %>
                                </div>
                            </div>
                        <% else %>
                            <div class="filtre_btn peche">
                                <div>
                                    <span class="close_icon"><%= image_tag "pictos/circle-xmark-regular.svg"%></span>
                                    <%= f.input :maison, as: :boolean,label:"Maisons", input_html: { data: {action: "change->filters#checkedSelect"},:checked => false } %>
                                </div>
                            </div>
                        <% end %>

                        <% if @type_bien == "appartement" || @type_bien == "all" || @type_bien == nil %>
                            <div class="filtre_btn filter_actif yellow">
                                <div>
                                    <span class="close_icon"><%= image_tag "pictos/circle-xmark-regular.svg"%></span>
                                    <%= f.input :appartement, as: :boolean,label:"Appartements", input_html: { data: {action: "change->filters#checkedSelect"},:checked => true } %>
                                </div>
                            </div>

                        <% else %>

                            <div class="filtre_btn yellow">
                                <div>
                                    <span class="close_icon"><%= image_tag "pictos/circle-xmark-regular.svg"%></span>
                                    <%= f.input :appartement, as: :boolean,label:"Appartements", input_html: { data: {action: "change->filters#checkedSelect"},:checked => false } %>
                                </div>
                            </div>

                        <% end %>

                        <% if @type_bien == "terrain" || @type_bien == "all" || @type_bien == nil %>
                            <div class="filtre_btn filter_actif green">
                                <div>
                                    <span class="close_icon"><%= image_tag "pictos/circle-xmark-regular.svg"%></span>
                                    <%= f.input :terrain, as: :boolean,label:"Terrains", input_html: { data: {action: "change->filters#checkedSelect"},:checked => true } %>
                                </div>
                            </div>
                        
                        <% else %>

                            <div class="filtre_btn green">
                                <div>
                                    <span class="close_icon"><%= image_tag "pictos/circle-xmark-regular.svg"%></span>
                                    <%= f.input :terrain, as: :boolean,label:"Terrains", input_html: { data: {action: "change->filters#checkedSelect"},:checked => true } %>
                                </div>
                            </div>

                        <% end %>

                        <% if @type_bien == "commerce" || @type_bien == "all" || @type_bien == nil %>
                            <div class="filtre_btn filter_actif dark-blue">
                                <div>
                                    <span class="close_icon"><%= image_tag "pictos/circle-xmark-regular.svg"%></span>
                                    <%= f.input :commerce, as: :boolean,label:"Commerces", input_html: { data: {action: "change->filters#checkedSelect"},:checked => true } %>
                                </div>
                            </div>
                        <% else %>
                            <div class="filtre_btn dark-blue">
                                <div>
                                    <span class="close_icon"><%= image_tag "pictos/circle-xmark-regular.svg"%></span>
                                    <%= f.input :commerce, as: :boolean,label:"Commerces", input_html: { data: {action: "change->filters#checkedSelect"},:checked => false } %>
                                </div>
                            </div>
                        <% end %>

                        <% if @type_bien == "immeuble" || @type_bien == "all" || @type_bien == nil %>
                            <div class="filtre_btn filter_actif grey">
                                <div>
                                    <span class="close_icon"><%= image_tag "pictos/circle-xmark-regular.svg"%></span>
                                    <%= f.input :immeuble, as: :boolean,label:"Immeubles", input_html: { data: {action: "change->filters#checkedSelect"},:checked => true } %>
                                </div>
                            </div>
                        <% else %>
                            <div class="filtre_btn grey">
                                <div>
                                    <span class="close_icon"><%= image_tag "pictos/circle-xmark-regular.svg"%></span>
                                    <%= f.input :immeuble, as: :boolean,label:"Immeubles", input_html: { data: {action: "change->filters#checkedSelect"},:checked => false } %>
                                </div>
                            </div>
                        <% end %>

                        <% if @type_bien == "parking" || @type_bien == "all" || @type_bien == nil %>
                            <div class="filtre_btn filter_actif purple">
                                <div>
                                    <span class="close_icon"><%= image_tag "pictos/circle-xmark-regular.svg"%></span>
                                    <%= f.input :parking, as: :boolean,label:"Parking/Box", input_html: { data: {action: "change->filters#checkedSelect"},:checked => true } %>
                                </div>
                            </div>
                        <% else %>
                            <div class="filtre_btn purple">
                                <div>
                                    <span class="close_icon"><%= image_tag "pictos/circle-xmark-regular.svg"%></span>
                                    <%= f.input :parking, as: :boolean,label:"Parking/Box", input_html: { data: {action: "change->filters#checkedSelect"},:checked => false } %>
                                </div>
                            </div>
                        <% end %>

                        

                        
                    </div>
                    <div class="hidden_filters">
                        <%= f.input :min_price %>
                        <%= f.input :max_price %>
                        <%= f.input :min_surface %>
                        <%= f.input :balcon,as: :boolean,input_html: { data: {action: "change->filters#checkedSelect"}} %>
                        <%= f.input :terrasse,as: :boolean %>
                        <%= f.input :garage,as: :boolean %>
                        <%= f.input :jardin,as: :boolean %>
                        <%= f.input :ascenseur,as: :boolean %>
                        <%= f.input :min_dpe, collection:["A","B","C","D","E","F","G"] %>
                        <%= f.input :min_ges, collection:["A","B","C","D","E","F","G"] %>
                    </div>
                    <%= f.button :submit %>
                <% end %>

                <%= link_to rent_filter_path(type_bien:nil), data: {turbo_method: :post,filters_target: "category_filtre", action:"click->filters#moreOptions"},class:"filtre_btn white filter_actif" do %>
                        <div>
                            <span class="close_icon"><%= image_tag "pictos/circle-plus-solid.svg"%></span>
                            <span>Plus de critères</span>
                        </div>
                <% end %>
                <button onclick="filtersDialog.showModal();" class="filtre_btn white filter_actif">
                    <div>
                            <span class="close_icon"><%= image_tag "pictos/circle-plus-solid.svg"%></span>
                            <span>Plus de critères</span>
                        </div>
                </button>
            </ul>

        </div>
    </section>
    <div class="annonces_index">
    <section class="list_annonces">
        <ul class="new_annonces" id="annonces_list_index">
            <%= render partial: "achats/annonces", locals: {annonces: @annonces}%>
        </ul>
    </section>
    <section class="carte_fixed">
        <div id="map"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
    </section> 
    </div>
</article>

<dialog id="filtersDialog">
            <p>Koor.fr Dialog demonstration</p>
            
            <form method="dialog">
                <button>Close the dialog</button>
            </form>
</dialog>
    

app/views/achats/rent_filter.html.erb
<h1>AAA</h1>

app/views/achats/rent_filter.turbo_stream.erb
<%= turbo_stream.update "annonces_list_index" do %>
  <%= render partial: "achats/annonces", locals: { annonces: @annonces } %>
<% end %>

app/views/achats/show.html.erb
<div id="#annonce">
    <%= render "shared/annonce", annonce: @annonce %>
</div>

app/views/achats/strasbourg.html.erb
<section class="quartier_intro inside petite_france">
    <div class="quartier_intro_mobile">
        <h1><%= image_tag "agences/strasbourg.png", width: 500, height:500, alt:"Achat & location d'appartements et maisons à Strasbourg";%></h1>
        <h2 class="titre_quartier_show">Strasbourg</h1>
    </div>
    <div class="quartier_intro_text">
        <%= sanitize @intro_text %>
    </div>
</section>
    <section class="inside">
        

        <ul class="filtre_tags quartiers_strasbourg">
            <% @quartiers.keys.each do |quartier_name| %>
                <li class="raccourci_achat"><%= link_to quartier_name, strasbourg_quartier_path(quartier_name.downcase.parameterize(separator: '-'))%></li>
            <% end %>
        </ul>
    </section>
    <div class="annonces_index">
    <section class="list_annonces">
        <ul class="new_annonces">
            <% @annonces.each do |annonce| %>
            <li>
            <%= link_to achat_show_path(annonce) do %>
            <%= render partial: "achats/annonce", locals: {annonce: annonce} %>
            <% end %>
            </li>
            <% end %>
        </ul>
        <div>
            <ul>
                <li>Alsace</li>
                <li>Bas-Rhin</li>
                <li>Haut-Rhin</li>
                <li>Strasbourg</li>
            </ul>
        </div>
    </section>
    <section class="carte_fixed">
        <div id="map"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
    </section> 
    </div>
    

app/views/achats/strasbourg_quartier.html.erb
<section class="quartier_intro inside petite_france">
    <div class="quartier_intro_mobile">
        <h1><%= image_tag @cover, width: 500, height:500,alt:"Achat & location d'appartements - quartier #{@quartier_name} - Strasbourg";%></h1>
        <h2 class="titre_quartier_show"><%= @quartier_name %></h1>
    </div>
    <div class="quartier_intro_text">
        <%= sanitize @quartier_text %>
    </div>
</section>
<section class="inside">
    <ul class="list_annonces three new_annonces">
            <% @annonces.each do |annonce| %>
            <li>
            <%= link_to achat_show_path(annonce) do %>
            <%= render partial: "achats/annonce", locals: {annonce: annonce} %>
            <% end %>
            </li>
            <% end %>
    </ul>
   
</section>
<section class="inside map_quartier">
    <div id="map"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</section>
<section class="inside">
    <%= render "autres_quartiers", locals: { quartiers: @autres_quartiers} %>
</section>

app/views/achats/turbo_list.html.erb
<turbo-frame id="view_more">
  <p>
    That's all! Nothing else to show.
  </p>
</turbo-frame>

<turbo-frame id="second_filtres">
  <ul>
    <p>filtres</p>
  </ul>
</turbo-frame>