config/routes.rb
Rails.application.routes.draw do

  devise_for :admins

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "pages#home"
  get 'pages/home'
  get 'pages/about'
  get '/contact', to: "pages#contact"
  post '/send', to:"pages#send_contact"
  get '/message_send', to: "pages#message_send"
  get '/gestion-locative', to:  "pages#gestion_locative"
  get '/gestion-locative/:ville',to: "pages#gestion_locative_ville", as: :gestion_loc_ville

  get '/mentions',to: "pages#mentions"
  get '/confidentialite', to: "pages#confidentialite"
  get '/cookies',to:"pages#cookies"
  get '/plan-site',to:"pages#plan_site"

  get 'components', to: "pages#components"

  resources :admins do
    resources :annonces
    #collection do
      #get "annonces", to: "admins#annonces"
    #end
  end
  get 'locations', to: "locations#index"
  get 'locations/appartements', to: "locations#appartements"
  get 'locations/maisons', to: "locations#maisons"

  get "commerces", to: "commerces#index"

  resources :agences do
    collection do
      get "agence-immobiliere-strasbourg", to: "agences#orangerie", as: "strasbourg"
      get "agence-immobiliere-strasbourg-neudorf", to: "agences#neudorf", as: "neudorf"
      get "agence-immobiliere-strasbourg-krutenau", to: "agences#krutenau", as: "krutenau"
      get "agence-immobiliere-strasbourg-orangerie", to: "agences#orangerie", as: "orangerie"
      get "agence-immobiliere-wissembourg", to: "agences#wissembourg", as: "wissembourg"
      get "agence-immobiliere-molsheim", to: "agences#molsheim", as: "molsheim"
      get "agence-immobiliere-colmar", to: "agences#colmar", as: "colmar"
      get "agence-immobiliere-haguenau", to: "agences#haguenau", as: "haguenau"
      get "agence-immobiliere-schiltigheim", to: "agences#schiltigheim", as: "schiltigheim"
      get "agence-immobiliere-altkirch", to: "agences#altkirch", as: "altkirch"
      get "agence-immobiliere-brumath", to: "agences#brumath", as: "brumath"
      get "agence-immobiliere-barr", to: "agences#barr", as: "barr"
      get "agence-immobiliere-erstein", to: "agences#erstein", as: "erstein"
      get "agence-immobiliere-cernay", to: "agences#cernay", as: "cernay"
    end
  end
  get "achat-immobilier", to: "achats#index", as: :annonces
  get "achat-immobilier/:id", to: "achats#show", as: :achat_show
  get "achat-appartements", to: "achats#appartements", as: :appartements
  post "rent-filter", to: "achats#rent_filter", as: :rent_filter
  get "achat-maisons", to: "achats#maisons", as: :maisons
  get "achat-terrains", to: "achats#terrains", as: :terrains
  get "achat-test", to: "achats#annonces_test"
  post "turbo_list", to: "achats#turbo_list"

  scope "achat" do
    get "/alsace", to: "achats#alsace"
    get "/bas-rhin", to: "achats#bas_rhin"
    get "/haut-rhin", to: "achats#haut_rhin"
    get "/strasbourg", to: "achats#strasbourg"
    get "/test", to: "achats#test"
    scope "strasbourg" do
      get '/:quartier', to: "achats#strasbourg_quartier", as: :strasbourg_quartier
    end
  end

  post "full_list", to: "pages#full_list"

  
end

app/views/shared/_annonce.html.erb
<section class="inside">
    <div class="annonce_show_photos" data-controller="annonce">
        <div class="cover">
            <% @annonce.photos.each do |photo| %>
                <%= image_tag photo, class: "cover-img", data: { annonce_target: "cover" } %>
            <% end %>
        </div>
        <ul class="carrousel_photos inside">
            <% @annonce.photos.each do |photo| %>
            <li class="carrousel_select" data-action="click->annonce#selectImg" data-annonce-target="image"><%= image_tag photo %></li>
            <% end %>
        </ul>
    </div>

</section>
<section class="inside">
    <div class="">
        <div class="annonce_entete">
            <h1 class="annonce_show_titre"><%= @annonce.titre %>|Titre</h1>
            <p><%= @annonce.surface.to_i %>m<sup>2</sup></p>
            <p><%= @annonce.price %>€</p>
        </div>
        <div class="ville">
            <p><%= @annonce.city %></p>
        </div>
        <div class="inside">
            <div class="energetique_barre dpe">
                <% ["a","b","c","d","e","f","g"].each do |letter| %>
                    <% if letter == @annonce.dpe.downcase %>
                        <span class="note <%= letter %> selected"><%= letter.capitalize %></span>
                    <% else %>
                        <span class="note <%= letter %>"><%= letter.capitalize %></span>
                    <% end %>
                <% end %>
            </div>
            <div class="energetique_barre ges">
                <% ["a","b","c","d","e","f","g"].each do |letter| %>
                    <% if letter == @annonce.ges.downcase %>
                        <span class="note <%= letter %> selected"><%= letter.capitalize %></span>
                    <% else %>
                        <span class="note <%= letter %>"><%= letter.capitalize %></span>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
    <p class="annonce_show_description"><%= @annonce.description %></p>
</section>
<section class="inside">
    <h2 class="titre styling">Descriptif</h2>
    
    <div class="table_description_annonce">
        <div><p>Surface: <%= @annonce.surface %> m<sup>2</sup></p></div>
        <div><p>Nombre de pièces: <%= @annonce.nb_pieces %></p></div>
        <div><p>Nombre d'étages: <%= @annonce.nb_etage %></p></div>
        <div><p>Chauffage: <%= @annonce.chauffage %></p></div>
        <div><p>Mode de chauffage: <%= @annonce.chauffage_mode %></p></div>
        <div><p>Etat général: <%= @annonce.etat_general %></p></div>
        <div><p>Année de construction: <%= @annonce.annee_construction.strftime("%Y") %></p></div>
        <div><p>Cave: <%= @annonce.cave == true ? "Oui": "Non" %></p></div>
        <div><p>Ascenseur: <%= @annonce.ascenseur == true ? "Oui": "Non" %></p></div>
        <div><p>Copropriété: <%= @annonce.copropriete == true ? "Oui" : "Non" %></p></div>
         <div><p>Cuisine équipée: <%= @annonce.cuisine_equipee == true ? "Oui" : "Non" %></p></div>
        <div><p>Jardin: <%= @annonce.jardin == true ? "Oui" : "Non" %></p></div>
        <div><p>Balcon: <%= @annonce.balcon == true ? "Oui" : "Non" %></p></div>
        <div><p>Terrasse: <%= @annonce.terrasse == true ? "Oui" : "Non" %></p></div>
         <div><p>Garage: <%= @annonce.garage == true ? "Oui" : "Non" %></p></div>
    </div>
</section>

<section class="inside">
    <div id="map" class="map_annonce"
        data-controller="map"
        data-map-markers-value="<%= @marker.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</section>
<section class="inside">
    <h2 class="titre styling">Autres annonces dans le secteur</h2>
</section>
<section class="inside">
    <turbo-frame id="first_frame">
        <%= button_to "View all", full_list_path, data:{turbo_frame:"second_frame"}, params:"click" %>
    </turbo-frame>
    <br>
    <hr>
    <div>
        <turbo-frame id="second_frame">
        </turbo-frame>
    </div>
</section>

app/views/shared/_footer.html.erb
<footer id="footer">
    <div class="inside">
        <ul>
            <li><%= link_to "Mentions légales", mentions_path %></li>
            <li><%= link_to "Politique de confidentialité", confidentialite_path %></li>
            <li><%= link_to "Gestion des cookies", cookies_path %></li>
            <li><%= link_to "Plan du site", plan_site_path %></li>
        </ul>
        <div class="social_links">
            <%= link_to "https://www.facebook.com/marineweishaar.agentimmo?locale=fr_FR" do %>
                <%= image_tag "pictos/facebook-brands-solid.svg"%>
            <% end %>
            <%= link_to "https://www.instagram.com/marine_weishaar_immobilier/" do %>
                <%= image_tag "pictos/instagram-brands-solid.svg"%>
            <% end %>
        </div>
        <%= link_to "https://www.immomann.com/" do %>
            <%= image_tag 'logo-blanc-immoman.png' %>
        <% end %>
    </div>
</footer>

app/views/shared/_info_window.html.erb
<h2><%= flat.titre %></h2>
<!--
<p><%= flat.address %></p>
-->

app/views/shared/_marker.html.erb
<span class="marker_map"><%= humanized_money flat.price %> €</span>

app/views/shared/_navbar.html.erb
    <div id="nav" data-controller="navbar">
        <div class="colorized-nav">
            <div class="inside">
                <% if params[:action] == "home" %>
                    <div class="logo">
                        <%= link_to root_path do %>
                        <h1>
                            <%= image_tag "logo-mw-immobilier-2.png",alt:"Marine Weishaar Immobilier" %>
                        </h1>
                        <% end %>
                    </div>
                <% else %>
                    <div class="logo">
                        <%= link_to root_path do %>
                            <%= image_tag "logo-mw-immobilier-2.png",alt:"logo Marine Weishaar" %>
                        <% end %>
                    </div>
                <% end %>
                <div class="header_cta">
                    <%= link_to "Mon espace pro",admins_path, class:"btn black" %>
                    <%= link_to "Nous contacter", contact_path, class:"btn black" %>
                </div>
                <div id="burger_menu" data-action="click->navbar#mobileMenu">
                    <svg xmlns="http://www.w3.org/2000/svg" height="32" width="28" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M0 96C0 78.3 14.3 64 32 64H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32C14.3 128 0 113.7 0 96zM0 256c0-17.7 14.3-32 32-32H416c17.7 0 32 14.3 32 32s-14.3 32-32 32H32c-17.7 0-32-14.3-32-32zM448 416c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32s14.3-32 32-32H416c17.7 0 32 14.3 32 32z"/></svg>
                </div>
            </div>
            
        </div>
        
        <nav class="nav__primary">
            <ul class="inside relat">
                <li data-action="mouseover->navbar#mouseOver mouseout->navbar#mouseOut">
                    <%= link_to "Acheter", annonces_path %>
                    <ul class="nav__secondary" data-navbar-target="volets">
                        <li><%= link_to "Appartements", appartements_path %></li>
                        <li><%= link_to "Maisons", maisons_path %></li>
                        <li><%= link_to "Terrains", terrains_path %></li>
                        <li><%= link_to "lien #"%></li>
                        <li><%= link_to "lien #"%></li>
                    </ul>
                </li>
                <li data-action="mouseover->navbar#mouseOver mouseout->navbar#mouseOut">
                    <%= link_to "Vendre" %>
                    <ul class="nav__secondary" data-navbar-target="volets">
                        <li><%= link_to "lien #"%></li>
                        <li><%= link_to "lien #"%></li>
                        <li><%= link_to "lien #"%></li>
                        <li><%= link_to "lien #"%></li>
                        <li><%= link_to "lien #"%></li>
                    </ul>
                </li>
                <li data-action="mouseover->navbar#mouseOver mouseout->navbar#mouseOut">
                    <%= link_to "Louer", locations_path %>
                    <ul class="nav__secondary" data-navbar-target="volets">
                        <li><%= link_to "Appartements", locations_appartements_path %></li>
                        <li><%= link_to "Maisons", locations_maisons_path %></li>
                        <li><%= link_to "lien #"%></li>
                        <li><%= link_to "lien #"%></li>
                        <li><%= link_to "lien #"%></li>
                    </ul>
                </li>
                <li><%= link_to "Gestion locative",gestion_locative_path %></li>
                <li data-action="mouseover->navbar#mouseOver mouseout->navbar#mouseOut">
                    <%= link_to "Investir" %>
                    <ul class="nav__secondary" data-navbar-target="volets">
                        <li><%= link_to "lien #"%></li>
                        <li><%= link_to "lien #"%></li>
                        <li><%= link_to "lien #"%></li>
                        <li><%= link_to "lien #"%></li>
                        <li><%= link_to "lien #"%></li>
                    </ul>
                </li>
                <li><%= link_to "Bureaux & commerces",commerces_path %></li>
                <li>
                    <%= link_to "Blog" %>
                </li>
            </ul>
            <div id="bg_grey" data-navbar-target="grey"></div>
        </nav>

        <div class="nav_mobile_volet" data-navbar-target="mobileVolet">
            <ul>
                <li data-action="click->navbar#voletNext">Acheter</li>
                <li data-action="click->navbar#voletNext">Louer</li>
                <li>Vendre</li>
                <li><%= link_to "Gestion locative",gestion_locative_path %></li>
                <li><%= link_to "Bureaux & commerces",commerces_path %></li>
                <div class="ctas">
                    <%= link_to "Nous contacter", contact_path, class:"btn black" %>
                    <%= link_to "Mon espace pro",admins_path, class:"btn black" %>
                </div>
            </ul>
        </div>
        <div class="nav_mobile_volet" data-navbar-target="mobileVolet">
            <ul>
                <li data-action="click->navbar#voletPrev">Retour</li>
                <li><%= link_to "Appartements",appartements_path %></li>
                <li><%= link_to "Maisons",maisons_path %></li>
                <li><%= link_to "Terrains",terrains_path %></li>
                <li><%= link_to "Toutes les annonces",annonces_path %></li>
            </ul>
        </div>
        <div class="nav_mobile_volet" data-navbar-target="mobileVolet">
            <ul>
                <li data-action="click->navbar#voletPrev">Retour</li>
                <li><%= link_to "Appartements",locations_appartements_path %></li>
                <li><%= link_to "Maisons",locations_maisons_path %></li>
                <li><%= link_to "Toutes les locations",locations_path %></li>
            </ul>
        </div>

    </div>